/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package max2;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tonyj
 */
public class Comprar extends javax.swing.JInternalFrame {
    public String iduser;
    /**
     * Creates new form Comprar
     */
    public Comprar() {
        initComponents();
        escribir();
        escribir1();
        panel1.setVisible(false);
        txtT.setVisible(false);
        desh();
       // tablah1.setBackground();
    }
       public void escribir1(){
        DefaultTableModel tb =  (DefaultTableModel) tablah1.getModel();
        int a = tablah1.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        tb.removeRow(tb.getRowCount()-1);
        }
        Max2 ok = new Max2();
        try {
            Max2.EscribirCliente(tablah1,txtT);
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void escribir(){
         DefaultTableModel tb =  (DefaultTableModel) tablah.getModel();
        int a = tablah.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        tb.removeRow(tb.getRowCount()-1);
        }
        Max2 ok = new Max2();
        try {
            Max2.EscribirProducto(tablah,txtT);
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        txtT = new javax.swing.JLabel();
        panel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablah = new javax.swing.JTable();
        txtbus = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        panel11 = new javax.swing.JPanel();
        txtprecio = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdesc = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        cmbmedida = new javax.swing.JComboBox<>();
        txtnom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btngua = new javax.swing.JButton();
        btncan = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        compra = new javax.swing.JTextField();
        panel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablah1 = new javax.swing.JTable();
        txtbus1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel1.add(txtT, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 490, 56, 31));

        panel12.setBackground(new java.awt.Color(0, 102, 102));

        tablah.setBackground(new java.awt.Color(204, 204, 204));
        tablah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Descripcion", "Medida", "Precio", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablahMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablah);

        txtbus.setBackground(new java.awt.Color(0, 102, 102));
        txtbus.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtbus.setToolTipText("Ingrese El Nombre\n");
        txtbus.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtbus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbusKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText("Buscar :");

        javax.swing.GroupLayout panel12Layout = new javax.swing.GroupLayout(panel12);
        panel12.setLayout(panel12Layout);
        panel12Layout.setHorizontalGroup(
            panel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel12Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbus, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        panel12Layout.setVerticalGroup(
            panel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel12Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtbus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
        );

        panel1.add(panel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 0, 670, 690));

        panel11.setBackground(new java.awt.Color(153, 153, 0));

        txtprecio.setEditable(false);
        txtprecio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtprecio.setEnabled(false);
        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Descripcion :");

        txtnumero.setEditable(false);
        txtnumero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtnumero.setEnabled(false);
        txtnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setEnabled(false);

        txtdesc.setEditable(false);
        txtdesc.setColumns(20);
        txtdesc.setRows(5);
        jScrollPane1.setViewportView(txtdesc);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero : ");

        cmbmedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG", "UNO", "LT", "MIN", "GLB" }));
        cmbmedida.setEnabled(false);
        cmbmedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmedidaActionPerformed(evt);
            }
        });

        txtnom.setEditable(false);
        txtnom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtnom.setEnabled(false);
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Unidad de medida : ");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre : ");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Precio de venta :");

        btngua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-carrito-de-compras-30.png"))); // NOI18N
        btngua.setText("Agregar a carrito");
        btngua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguaActionPerformed(evt);
            }
        });

        btncan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cerrar-ventana-20.png"))); // NOI18N
        btncan.setText("Cancelar");
        btncan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncanActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cantidad de compra  :");

        compra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        compra.setEnabled(false);
        compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel11Layout = new javax.swing.GroupLayout(panel11);
        panel11.setLayout(panel11Layout);
        panel11Layout.setHorizontalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel18)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmedida, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compra, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel11Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(btngua)
                .addGap(18, 18, 18)
                .addComponent(btncan, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        panel11Layout.setVerticalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel11Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbmedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(46, 46, 46)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngua))
                .addGap(125, 125, 125))
        );

        panel1.add(panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 690));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 690));

        tablah1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Documento", "Nombre", "Telefono", "Email", "Primer Apellido", "Segundo Apellido", "Tipo Documento", "codigo", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablah1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablah1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablah1);

        txtbus1.setBackground(new java.awt.Color(240, 240, 240));
        txtbus1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtbus1.setToolTipText("Ingrese Identificacion");
        txtbus1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtbus1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbus1KeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setText("Buscar :");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtbus1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablah1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablah1MouseClicked
        // TODO add your handling code here:
        int num;

        String doc,nom,tel,mail,ap1,ap2,tipodoc,cod,dir;
        num=tablah1.rowAtPoint(evt.getPoint());
        // System.out.print(num=tablah.rowAtPoint(evt.getPoint()));

        doc = tablah1.getModel().getValueAt(num, 0).toString();
        nom = tablah1.getModel().getValueAt(num, 1).toString();
        tel = tablah1.getModel().getValueAt(num, 2).toString();
        mail = tablah1.getModel().getValueAt(num, 3).toString();
        ap1 = tablah1.getModel().getValueAt(num, 4).toString();
        ap2 = tablah1.getModel().getValueAt(num, 5).toString();
        tipodoc = tablah1.getModel().getValueAt(num, 6).toString();
        cod = tablah1.getModel().getValueAt(num, 7).toString();
        dir = tablah1.getModel().getValueAt(num, 8).toString();
         panel1.setVisible(true);
         panel2.setVisible(false);
         iduser=doc;
    }//GEN-LAST:event_tablah1MouseClicked

    private void txtbus1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbus1KeyReleased
        // TODO add your handling code here:
        if(txtbus1.getText().equalsIgnoreCase("")){
            escribir1();
        }else{
            DefaultTableModel tb =  (DefaultTableModel) tablah1.getModel();
            int a = tablah1.getRowCount()-1;
            for (int i = a; i >= 0; i--) {
                tb.removeRow(tb.getRowCount()-1);
            }

            String nombres[]= new String [10];
            String bus=txtbus1.getText();
            Max2 ok = new Max2();
            try {
                Max2.EscribirClienteBusqueda(tablah1,bus);
            } catch (SQLException ex) {
                Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_txtbus1KeyReleased

    private void compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compraActionPerformed

    private void btncanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncanActionPerformed
        // TODO add your handling code here:
        desh();
        compra.setText("");
        compra.setEditable(false);
        compra.setEnabled(false);
    }//GEN-LAST:event_btncanActionPerformed

    private void btnguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguaActionPerformed
        String nom,num,desc,med,precio,can;
        num=txtnumero.getText();
        desc=txtdesc.getText();
        med=cmbmedida.getSelectedItem().toString();
        nom=txtnom.getText();
        precio=txtprecio.getText();
        can=compra.getText();
        if(can.equals("")){
            JOptionPane.showMessageDialog(null, "Dato de 'Cantidad' incorrecto");
        }else{
            if(Integer.parseInt(can)==0){
                JOptionPane.showMessageDialog(null, "Dato de 'Cantidad' incorrecto");
            }else{
                Max2 ok = new Max2();
                int gasto=(Integer.parseInt(precio)*Integer.parseInt(can));
                try {
                    ok.carrito(iduser,nom,precio,can,num,gasto);
                    JOptionPane.showMessageDialog(null, "Agregado a la Cuenta");
                } catch (SQLException ex) {
                    Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        escribir();
        desh();

    }//GEN-LAST:event_btnguaActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void cmbmedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmedidaActionPerformed

    private void txtnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void txtbusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusKeyTyped

    private void txtbusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusKeyReleased
        // TODO add your handling code here:
        if(txtbus.getText().equalsIgnoreCase("")){
            escribir();
        }else{
            DefaultTableModel tb =  (DefaultTableModel) tablah.getModel();
            int a = tablah.getRowCount()-1;
            for (int i = a; i >= 0; i--) {
                tb.removeRow(tb.getRowCount()-1);
            }

            String nombres[]= new String [10];
            String bus=txtbus.getText();
            Max2 ok = new Max2();
            try {
                Max2.EscribirProductoBusqueda(tablah,bus);
            } catch (SQLException ex) {
                Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtbusKeyReleased

    private void tablahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablahMouseClicked
        // TODO add your handling code here:

        int num;

        String nom,numero,desc,precio,cmb;
        num=tablah.rowAtPoint(evt.getPoint());
        // System.out.print(num=tablah.rowAtPoint(evt.getPoint()));

        nom = tablah.getModel().getValueAt(num, 4).toString();
        numero = tablah.getModel().getValueAt(num, 0).toString();
        desc = tablah.getModel().getValueAt(num, 1).toString();
        cmb = tablah.getModel().getValueAt(num, 2).toString();
        precio = tablah.getModel().getValueAt(num, 3).toString();
        // Object var=tablah.getColumnModel().getColumn(0);
        txtnom.setText(nom);
        txtnumero.setText(numero);
        txtdesc.setText(desc);
        txtprecio.setText(precio);
        cmbmedida.setSelectedItem(cmb);
        compra.setEditable(true);
        compra.setEnabled(true);
        hab();
    }//GEN-LAST:event_tablahMouseClicked
    public void desh(){
    txtnom.setEnabled(false);
     txtnumero.setEnabled(false);
     cmbmedida.setEnabled(false);
       txtprecio.setEnabled(false);
       txtdesc.setEnabled(false);
        btngua.setEnabled(false);
       btncan.setEnabled(false);
         compra.setText("");
         compra.setEditable(false);
         compra.setEnabled(false);
    }
      public void hab(){
    txtnom.setEnabled(true);
     txtnumero.setEnabled(true);
      txtdesc.setEnabled(true);
     txtnom.setEnabled(true);
       txtprecio.setEnabled(true);
       btngua.setEnabled(true);
       btncan.setEnabled(true);
         compra.setText("");
         compra.setEditable(true);
         compra.setEnabled(true);
    }
       public void limpiar(){
    txtnom.setText("");
     txtnumero.setText("");
      txtdesc.setText("");
       txtprecio.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncan;
    private javax.swing.JButton btngua;
    private javax.swing.JComboBox<String> cmbmedida;
    private javax.swing.JTextField compra;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel11;
    private javax.swing.JPanel panel12;
    private javax.swing.JPanel panel2;
    private javax.swing.JTable tablah;
    private javax.swing.JTable tablah1;
    private javax.swing.JLabel txtT;
    private javax.swing.JTextField txtbus;
    private javax.swing.JTextField txtbus1;
    private javax.swing.JTextArea txtdesc;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
